apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260509-224616-yd3twnn6dzry-service
spec:
  selector:
    app: enterprise-system-20260509-224616-yd3twnn6dzry
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
